version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: bill_manager
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: bill-manager_api:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bill_manager
      SPRING_DATASOURCE_USERNAME: postgress
      SPRING_DATASOURCE_PASSWORD: 123456

volumes:
  postgres_data:
